<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SWP391.Group2.Domain\SWP391.Group2.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Dashboards\Commands\" />
    <Folder Include="Features\Snapshots\Commands\" />
  </ItemGroup>

</Project>
